/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  // But you can create a sidebar manually
  documentation: [
    {
      type: "category",
      label: "Introduction",
      items: [
        {
          type: "autogenerated",
          dirName: "introduction",
        },
      ],
    },
    {
      type: "category",
      label: "Hubs Subscription",
      items: [
        {
          type: "autogenerated",
          dirName: "subscription",
        },
      ],
    },
    {
      type: "category",
      label: "Hubs Fundamentals",
      items: [
        {
          type: "autogenerated",
          dirName: "fundamentals",
        },
      ],
    },
    {
      type: "category",
      label: "For Creators",
      items: [
        {
          type: "autogenerated",
          dirName: "creators",
        },
      ],
    },
    {
      type: "category",
      label: "For Developers",
      items: [
        {
          type: "autogenerated",
          dirName: "developers",
        },
      ],
    },
    {
      type: "category",
      label: "Documentation Archive",
      items: [
        {
          type: "autogenerated",
          dirName: "archive",
        },
      ],
    },
  ],
};

export default sidebars;
