/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Mozilla Hubs",
  "tagline": "Hold tight as we get our docs in a row 🦆🦆🦆",
  "favicon": "img/favicon.ico",
  "staticDirectories": [
    "static"
  ],
  "url": "https://hubs.mozilla.com",
  "baseUrl": "/docs/",
  "organizationName": "Mozilla",
  "projectName": "hubs-docs",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.js",
          "editUrl": "https://github.com/MozillaReality/hubs-docs/"
        },
        "blog": {
          "showReadingTime": true,
          "editUrl": "https://github.com/MozillaReality/hubs-docs/"
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/hubs-business-45cd024f866b70dd21e23834458cc9ea.jpeg",
    "stylesheets": [
      "/css/custom.css"
    ],
    "navbar": {
      "title": "",
      "logo": {
        "alt": "Hubs by Mozilla Logo",
        "src": "img/logo-light.svg",
        "srcDark": "img/logo-dark.svg",
        "href": "https://hubs.mozilla.com/docs"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "documentation",
          "position": "left",
          "label": "Documentation"
        },
        {
          "type": "dropdown",
          "label": "Learning",
          "position": "left",
          "items": [
            {
              "label": "Community Discord",
              "href": "https://discord.gg/6WhYg4HC"
            },
            {
              "label": "Creator Labs Blog",
              "href": "https://hubs.mozilla.com/labs"
            },
            {
              "label": "Hubs YouTube",
              "href": "https://www.youtube.com/c/mozillahubs"
            }
          ]
        },
        {
          "type": "dropdown",
          "label": "Hubs Products",
          "position": "left",
          "items": [
            {
              "label": "Hubs Demo Server",
              "href": "https://hubs.mozilla.com/demo"
            },
            {
              "label": "Managed Subscription",
              "href": "https://hubs.mozilla.com/#subscribe"
            },
            {
              "label": "Hubs Cloud Community Edition",
              "href": "https://hubs.mozilla.com/labs/welcoming-community-edition/"
            }
          ]
        },
        {
          "href": "https://github.com/MozillaReality/hubs-docs",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Introduction",
              "to": "/docs/docs/introduction/what-is-hubs"
            },
            {
              "label": "Hubs Subscription",
              "to": "/docs/docs/subscription/choosing-subscription"
            },
            {
              "label": "Hubs Fundamentals",
              "to": "/docs/docs/fundamentals/getting-started"
            },
            {
              "label": "For Creators",
              "to": "/docs/docs/category/spoke"
            },
            {
              "label": "For Developers",
              "to": "/docs/docs/category/development-basics"
            },
            {
              "label": "Documentation Archive",
              "to": "/docs/docs/archive/discord-bot"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Discord",
              "href": "https://discord.gg/6WhYg4HC"
            },
            {
              "label": "Creator Labs",
              "href": "https://hubs.mozilla.com/labs"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/MozillaHubs"
            },
            {
              "label": "LinkedIn",
              "href": "https://www.linkedin.com/products/mozilla-corporation-mozilla-hubs"
            }
          ]
        },
        {
          "title": "Hubs Services",
          "items": [
            {
              "label": "Hubs Demo Server",
              "href": "https://hubs.mozilla.com/spoke"
            },
            {
              "label": "Hubs Managed Subscription",
              "href": "https://hubs.mozilla.com/#subscribe"
            },
            {
              "label": "Hubs Cloud Community Edition",
              "href": "https://hubs.mozilla.com/labs/welcoming-community-edition/"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2024 Mozilla Corporation. Hubs Documentation available under the Creative Commons Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0) license."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    }
  }
};
