/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: 'category',
      label: 'Introduction',
      items: [
        'welcome',
        'intro-hubs',
        'intro-spoke',
        'intro-avatars',
        'intro-events'
      ],
    },
    {
      type: 'category',
      label: 'Setting Up Your Hub',
      items: [
        'beginners-guide-to-CE',
        'set-up-SMTP-email-service',
        'download-and-install-doctl',
        'whats-next',
        'faq',
        'how-to-backup-your-Hubs-instance',
        'regenerating-ssl-certificates',
        // 'setup-choosing',
        // 'setup-creating',
        // 'setup-updating',
        'setup-configuring-content',
        // 'setup-custom-domain',
        // 'setup-custom-client',
        'setup-faq',
        'setup-contact',
        // 'setup-learning',
      ],
    },
    {
      type: 'category',
      label: 'Hubs Fundamentals',
      items: [
        'hubs-create-join-rooms',
        'hubs-features',
        'sharing-avatar-links-privately',
        'hubs-user-settings',
        'hubs-room-settings',
        'hubs-controls',
        'hubs-discord-bot',
        'hubs-troubleshooting',
        'hubs-faq',
        // 'download-data',
      ],
    },
    {
      type: 'category',
      label: 'Spoke Documentation',
      items: [
        'spoke-creating-projects',
        'spoke-user-interface',
        'spoke-controls',
        'spoke-adding-scene-content',
        'spoke-architecture-kit',
        'spoke-grid',
        'spoke-skyboxes',
        'lighting-and-shadows',
        'physics-and-navigation',
        'spoke-publish-scenes',
      ],
    },
    {
      type: 'category',
      label: 'For Creators',
      items: [
        'creators-advanced-avatar-customization',
        'creators-linking-rooms',
        'creators-using-the-blender-gltf-exporter',
        'creators-blender-components',
        'spoke-optimization',
        'creators-content-guidelines',
        'intro-behavior-graphs',
      ],
    },
    {
      type: 'category',
      label: 'For Developers',
      items: [
        'system-overview',
        'build-custom-client',
        'contributing',
        'hubs-query-string-parameters',
        'github-workflows',
      ],
    },
    {
      type: 'category',
      label: 'Hubs Client development',
      items: [
        'dev-client-basics',
        'dev-client-gameplay',
        'dev-client-interactivity',
        'dev-client-networking',
      ],
    },
    {
      type: 'category',
      label: 'Hubs Admin Panel',
      items: [
        'admin-intro',
        'admin-getting-started',
        // 'hubs-cloud-faq',
        'admin-importing-content',
        // 'hubs-cloud-asset-packs',
        // 'hubs-cloud-customizing-look-and-feel',
        'admin-customizing-themes',
        'admin-managing-content',
        'admin-adding-administrators',
        'admin-limiting-user-access',
        'admin-permissive-rooms',
        // 'hubs-cloud-third-party-integrations',
        'admin-enable-scene-editor',
        // 'hubs-cloud-custom-smtp',
        // 'hubs-cloud-discord-bot',
        // 'hubs-cloud-accessing-servers',
        // 'hubs-cloud-content-cdn',
        // 'hubs-cloud-custom-clients',
        // 'hubs-cloud-branding',
      ],
    },
    // {
      // type: 'category',
      // label: 'Hubs Cloud AWS',
      // items: [
        // 'hubs-cloud-aws-quick-start',
        // 'hubs-cloud-aws-domain-recipes',
        // 'hubs-cloud-aws-existing-domain',
        // 'hubs-cloud-aws-existing-email-provider',
        // 'hubs-cloud-aws-updating-the-stack',
        // 'hubs-cloud-aws-backup-and-restore',
        // 'hubs-cloud-aws-troubleshooting',
        // 'hubs-cloud-aws-known-issues',
        // 'hubs-cloud-aws-architecture',
        // 'hubs-cloud-aws-costs',
        // 'hubs-cloud-aws-estimated-cost-charts',
        // 'hubs-cloud-aws-estimated-ccu-limits',
      // ],
    // },
    // {
      // type: 'doc',
      // id: 'hubs-cloud-do-quick-start',
      // label: 'Hubs Cloud DigitalOcean'
    // },
  ],
};

module.exports = sidebars;
